name: Java Static Analysis

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Set up JDK 17 with Maven cache
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Set NVD API Key
        env:
          NVD_API_KEY: "0574a531-3097-4bd4-8777-e72d99aa6bed"  # 直接在这里设置环境变量
        run: |
          echo "NVD_API_KEY is set"
          # 这里可以使用 $NVD_API_KEY 作为环境变量

      - name: Run Maven build and static analysis
        run: |
          mvn clean verify -DskipTests

      - name: Upload analysis reports
        uses: actions/upload-artifact@v4
        with:
          name: analysis-reports
          path: target/reports/checkstyle.html  # 修改为实际生成的 HTML 文件路径
          retention-days: 7
          if-no-files-found: warn